/* SPDX-License-Identifier: MIT */

#ifndef DT_BINDINGS_TB_ACTIONS_H
#define DT_BINDINGS_TB_ACTIONS_H

// #define TB_INC_BASE_SCALE       0
// #define TB_DEC_BASE_SCALE       1
// #define TB_INC_FREQUENCY_THRESHOLD   2
// #define TB_DEC_FREQUENCY_THRESHOLD   3
// #define TB_INC_SMOOTHING_FACTOR 4
// #define TB_DEC_SMOOTHING_FACTOR 5
// #define TB_INC_INTERPOLATION_STEPS 6
// #define TB_DEC_INTERPOLATION_STEPS 7
// #define TB_INC_EXPONENTIAL_BASE 8
// #define TB_DEC_EXPONENTIAL_BASE 9

#endif /* DT_BINDINGS_TB_ACTIONS_H */
