/* SPDX-License-Identifier: MIT */

#ifndef DT_BINDINGS_TRACKBALL_ACTIONS_H
#define DT_BINDINGS_TRACKBALL_ACTIONS_H

#define TB_INC_BASE_SCALE       0
#define TB_DEC_BASE_SCALE       1
#define TB_INC_MOVEMENT_HISTORY_SIZE       2
#define TB_DEC_MOVEMENT_HISTORY_SIZE       3
#define TB_INC_FREQUENCY_THRESHOLD   4
#define TB_DEC_FREQUENCY_THRESHOLD   5

#endif /* DT_BINDINGS_TRACKBALL_ACTIONS_H */
