/* SPDX-License-Identifier: MIT */

#ifndef DT_BINDINGS_TRACKBALL_ACTIONS_H
#define DT_BINDINGS_TRACKBALL_ACTIONS_H

#define TB_INC_BASE_SCALE       0
#define TB_DEC_BASE_SCALE       1
#define TB_INC_FREQUENCY_THRESHOLD   2
#define TB_DEC_FREQUENCY_THRESHOLD   3

#endif /* DT_BINDINGS_TRACKBALL_ACTIONS_H */
